# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parameters.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from function import ndarray_pb2 as ndarray__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='parameters.proto',
  package='parameter',
  syntax='proto3',
  serialized_pb=_b('\n\x10parameters.proto\x12\tparameter\x1a\rndarray.proto\"T\n\nParameters\x12)\n\x08\x64\x61tasets\x18\x01 \x03(\x0b\x32\x17.parameter.NDArrayBytes\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05ratio\x18\x03 \x01(\x02\x62\x06proto3')
  ,
  dependencies=[ndarray__pb2.DESCRIPTOR,])




_PARAMETERS = _descriptor.Descriptor(
  name='Parameters',
  full_name='parameter.Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datasets', full_name='parameter.Parameters.datasets', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='parameter.Parameters.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ratio', full_name='parameter.Parameters.ratio', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=130,
)

_PARAMETERS.fields_by_name['datasets'].message_type = ndarray__pb2._NDARRAYBYTES
DESCRIPTOR.message_types_by_name['Parameters'] = _PARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Parameters = _reflection.GeneratedProtocolMessageType('Parameters', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETERS,
  __module__ = 'parameters_pb2'
  # @@protoc_insertion_point(class_scope:parameter.Parameters)
  ))
_sym_db.RegisterMessage(Parameters)


# @@protoc_insertion_point(module_scope)
