#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-receive".

echo 'hook start'
echo $(whoami)
GIT_SERVER_DIR=/var/www/git_server/
cd ${GIT_SERVER_DIR}
python3.6 messager.py ${GIT_PUSH_OPTION_0}
echo 'hook end'
