import CONSTANT from '../constants'

module.exports = {
  name: "Golder's Green",
  prefix: 'antdAdmin',
  footerText: "Golder's Green Datalab  © 2017",
  logo: '/logo.png',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  baseURL: 'http://localhost:8000/api/v1',
  YQL: ['http://www.zuimeitianqi.com'],
  CORS: [CONSTANT.flaskServer],
  openPages: ['/login'],
  apiPrefix: '/api/v1',
  //jupyterUrl: CONSTANT.,
  jupyterServer: CONSTANT.jupyterServer,
  api: {
    userLogin: '/user/login',
    refreshToken: '/refresh_token',
    userLogout: '/user/logout',
    userInfo: '/userInfo',
    users: '/users',
    user: '/user/:id',
    dashboard: '/dashboard',
    files: '/file/files',
    getStagingData: '/staging_data/staging_data_sets',
    // fileList: '/file/list_files_by_user_ID',
    // dataImport: '/data/import_data_from_file_id',
    dataSets: '/data/data_sets',
    projects: '/project/projects',
    publish: '/project/publish',
    unpublish: '/project/unpublish',
    fork : '/project/fork',
    toolkits: '/toolkit/toolkits/public',
    // projectCreate: '/project/create_project',
    getDataFields: '/data/data_sets/fields',
    neuralStyle: '/model/neural_style',
    servedModel: '/served_model',
    allModels: '/served_models'
  },
}
