module.exports = {
  name: "Golder's Green",
  prefix: 'antdAdmin',
  footerText: "Golder's Green Datalab  © 2017",
  logo: '/logo.png',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  baseURL: 'http://localhost:8000/api/v1',
  YQL: ['http://www.zuimeitianqi.com'],
  CORS: ['http://localhost:5000'],
  openPages: ['/login'],
  apiPrefix: '/api/v1',
  api: {
    userLogin: '/user/login',
    refreshToken: '/refresh_token',
    userLogout: '/user/logout',
    userInfo: '/userInfo',
    users: '/users',
    user: '/user/:id',
    dashboard: '/dashboard',
    fileUpload: '/file/upload_file',
    fileList: '/file/list_files_by_user_ID',
    dataImport: '/data/import_data_from_file_id',
    dataSets: '/data/list_data_sets_by_user_ID',
    projects: '/project/list_projects_by_user_ID',
    projectCreate: '/project/create_project'
  },
}
