import CONSTANT from '../constants'
import logo from '../blue-logo.png'
import whiteLogo from '../white-logo.png'

module.exports = {
  name: "MO",
  prefix: 'antdAdmin',
  footerText: "MO Datalab  © 2017",
  logo: logo,
  whiteLogo: whiteLogo,
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  baseURL: 'http://localhost:8000/api/v1',
  YQL: ['http://www.zuimeitianqi.com'],
  CORS: CONSTANT.apiPrefix,
  hubPrefix: '/hub_api',
  openPages: ['/login'],
  // apiPrefix: '/api/v1',
  //jupyterUrl: CONSTANT.,
  jupyterServer: CONSTANT.jupyterServer,
  kubeServer: CONSTANT.kubeServer,
  api: {
    userLogin: '/user/login',
    refreshToken: '/refresh_token',
    userLogout: '/user/logout',
    userInfo: '/userInfo',
    users: '/users',
    user: '/user/:id',
    dashboard: '/dashboard',
    files: '/file/files',
    getStagingData: '/staging_data/staging_data_sets',
    projectJobs: '/project/jobs',
    // fileList: '/file/list_files_by_user_ID',
    // dataImport: '/data/import_data_from_file_id',
    dataSets: '/data/data_sets',
    projects: '/project/projects',
    publish: '/project/publish',
    unpublish: '/project/unpublish',
    fork : '/project/fork',
    toolkits: '/toolkit/toolkits/public',
    models: '/model/models/public',
    // projectCreate: '/project/create_project',
    getDataFields: '/data/data_sets/fields',
    neuralStyle: '/model/neural_style',
    servedModel: '/served_model',
    allModels: '/served_models',
    publicServedModels:'/public_served_models',
    playground: '/project/playground/',
  },
}
